CREATE BIGFILE TABLESPACE TS_AUDITORIA DATAFILE 
  	'+DGDATA1' SIZE 100M AUTOEXTEND ON NEXT 1M MAXSIZE UNLIMITED
	LOGGING
	ONLINE
	EXTENT MANAGEMENT LOCAL AUTOALLOCATE
	BLOCKSIZE 16K
	SEGMENT SPACE MANAGEMENT AUTO
	FLASHBACK ON;
